#!/usr/bin/env node
// Create a standalone snippet with tracking support.
//
// Usage:
//   node create_snippet.mjs [--owner-pubkey 0x...] [--signer-policy owner|seller_agent] [--dimensions 300x250]
//
// Notes:
//   snippet_id is generated by the backend; clients only request creation.
//   status is backend-managed and defaults to inactive.
//
// Environment:
//   TRACKING_URL (default: http://localhost:4000)
import { parseArgs } from "node:util";
import { skillsConfig } from "../../config.js";

const TRACKING_URL = skillsConfig.trackingUrl;

const { values } = parseArgs({
  options: {
    "owner-pubkey": { type: "string" },
    "signer-policy": { type: "string" },
    dimensions: { type: "string" },
  },
});

const signerPolicy = values["signer-policy"]
  ? String(values["signer-policy"])
  : "owner";

if (signerPolicy !== "owner" && signerPolicy !== "seller_agent") {
  process.stderr.write(
    JSON.stringify({
      error: "--signer-policy must be owner or seller_agent",
    }) + "\n",
  );
  process.exit(1);
}

const body = {
  owner_pubkey: values["owner-pubkey"]
    ? String(values["owner-pubkey"])
    : undefined,
  signer_policy: signerPolicy,
  dimensions: values.dimensions ? String(values.dimensions) : undefined,
};

try {
  const response = await fetch(`${TRACKING_URL.replace(/\/+$/, "")}/snippets`, {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify(body),
  });
  const data = await response.json();
  if (!response.ok) {
    process.stderr.write(
      JSON.stringify({
        error: "snippet create failed",
        status: response.status,
        detail: data,
      }) + "\n",
    );
    process.exit(1);
  }
  console.log(JSON.stringify(data));
} catch (err) {
  process.stderr.write(
    JSON.stringify({
      error: err instanceof Error ? err.message : String(err),
    }) + "\n",
  );
  process.exit(1);
}
